version: '3'
services:
  couchbase-node1:
    image: couchbase:enterprise
    environment:
      - TYPE=PRIMARY
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - ./couchbase-data/node1:/opt/couchbase/var
    networks:
      couchbase-cluster:
        aliases:
          - couchbase-node1.localdomain

  couchbase-node2:
    image: couchbase:enterprise
    environment:
      - TYPE=WORKER
    volumes:
      - ./couchbase-data/node2:/opt/couchbase/var
    networks:
      couchbase-cluster:
        aliases:
          - couchbase-node2.localdomain

  couchbase-node3:
    image: couchbase:enterprise
    environment:
      - TYPE=WORKER
    volumes:
      - ./couchbase-data/node3:/opt/couchbase/var
    networks:
      couchbase-cluster:
        aliases:
          - couchbase-node3.localdomain    



  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: apple@26j
      MYSQL_DATABASE: privatelearningv2
      MYSQL_USER: aakash.kumar
      MYSQL_PASSWORD: apple26j
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - docker-network



  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vaulttoken
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:9200"
    ports:
      - "9200:9200"
    volumes:
      - ./vault-data:/vault/file
    networks:
      - docker-network

volumes:
  couchbase-data:
  mysql-data:
  vault-data:

networks:
  couchbase-cluster:
    driver: bridge
  docker-network:
    driver: bridge
