version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: apple@26j
      MYSQL_DATABASE: privatelearningv2
      MYSQL_USER: aakash.kumar
      MYSQL_PASSWORD: apple26j
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vaulttoken
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:9200"
    ports:
      - "9200:9200"
    volumes:
      - ./vault-data:/vault/file

  ### [START] Keycloak ###
  postgresql:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: elestio/keycloak:${SOFTWARE_VERSION_TAG}
    restart: always
    entrypoint: "/opt/keycloak/bin/kc.sh start --hostname-strict=false --http-enabled=true --proxy edge"
    env_file:
      - .env
    ports:
      - "9300:8080"
      #- "172.17.0.1:8080:8080"
    environment:
      - KEYCLOAK_LOGLEVEL=ALL
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HTTP_ENABLED=true
      - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN_USER
      - KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KC_DB_USERNAME=$POSTGRES_USER
      - KC_DB_PASSWORD=$POSTGRES_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=$POSTGRES_DB
      - KC_DB_URL_PORT=5432
      - KC_DB_SCHEMA=public
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_PROXY=edge
      - KEYCLOAK_EXTRA_ARGS=--auto-build
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0
    depends_on:
      - postgresql
    networks:
      - keycloak-network
  ### [END] Keycloak ###

volumes:
  mysql-data:
  vault-data:

networks:
  keycloak-network:
    driver: bridge
