version: '3'
services:
  # ################# #
  # Couchbase cluster #
  # ################# #
  couchbase-node1:
    image: couchbase:enterprise
    environment:
      - TYPE=PRIMARY
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - ./_docker-data/couchbase-data/node1:/opt/couchbase/var
    networks:
      couchbase-cluster:
        aliases:
          - couchbase-node1.localdomain

  #couchbase-node2:
  #  image: couchbase:enterprise
  #  environment:
  #    - TYPE=WORKER
  #  volumes:
  #    - ./_docker-data/couchbase-data/node2:/opt/couchbase/var
  #  networks:
  #    couchbase-cluster:
  #      aliases:
  #        - couchbase-node2.localdomain

  #couchbase-node3:
  #  image: couchbase:enterprise
  #  environment:
  #    - TYPE=WORKER
  #  volumes:
  #    - ./_docker-data/couchbase-data/node3:/opt/couchbase/var
  #  networks:
  #    couchbase-cluster:
  #      aliases:
  #        - couchbase-node3.localdomain    


  # ##### #
  # MYSQL #
  # ##### #
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: apple26j
      MYSQL_DATABASE: privatelearningv2
      MYSQL_USER: aakash.kumar
      MYSQL_PASSWORD: apple26j
    ports:
      - "3306:3306"
    volumes:
      - ./_docker-data/mysql-data:/var/lib/mysql
    networks:
      - docker-network


  # ##### #
  # VAULT #
  # ##### #
  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vaulttoken
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:9200"
    ports:
      - "9200:9200"
    volumes:
      - ./_docker-data/vault-data:/vault/file
    networks:
      - docker-network



volumes:
  couchbase-data:
  mysql-data:
  vault-data:

networks:
  couchbase-cluster:
    driver: bridge
  docker-network:
    driver: bridge
