cloud:
  aws:
    region:
      static: us-west-1  
    credentials:
      access-key: 
      secret-key: 


control-timings:
  sessions:
    time-limit-mins: 30
    break-time-mins: 10

  weekdays:
    total-time-limit-hr: 3
    timings:
      start: "15:30"
      end: "21:00"
  weekends-holidays:
    total-time-limit-hr: 5
    timings:
      start: "09:00"
      end: "21:00"
